### ISSUE TITLE
Maximum call stack size exceeded/Unhandled stream error in pipe while running npm run download

### ISSUE THREAD

**Issue by easherma** [pelias/whosonfirst#102]
```
> node download_data.js

starting borough
starting continent
starting country
starting county
starting dependency
starting disputed
starting localadmin
starting locality
starting macrocounty
starting macroregion
starting neighbourhood
starting region
done borough
done disputed
done dependency
done macrocounty
done continent
done macroregion
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

RangeError: Maximum call stack size exceeded
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at onheader (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:122:12)
    at Extract._write (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:243:8)
    at Extract._continue (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:207:28)
    at oncontinue (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:64:10)
    at onunlock (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:70:24)
    at handleEntry (/data/pelias-2/whosonfirst/download_data.js:47:3)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)

npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "download"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! pelias-whosonfirst@1.0.0 download: `node download_data.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pelias-whosonfirst@1.0.0 download script 'node download_data.js'.
npm ERR! This is most likely a problem with the pelias-whosonfirst package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node download_data.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pelias-whosonfirst
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pelias-whosonfirst
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/pelias-2/whosonfirst/npm-debug.log
```

**Comment by orangejulius** [comment]
I'm also this. Removing the try/catch block around the erroring code reveals the following stack trace:

```
RangeError: Maximum call stack size exceeded
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.mkdirsSync (/home/julian/repos/pelias/whosonfirst/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
    at handleEntry (/home/julian/repos/pelias/whosonfirst/download_data.js:30:10)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at onheader (/home/julian/repos/pelias/whosonfirst/node_modules/tar-stream/extract.js:171:12)
    at Extract._write (/home/julian/repos/pelias/whosonfirst/node_modules/tar-stream/extract.js:243:8)
    at Extract._continue (/home/julian/repos/pelias/whosonfirst/node_modules/tar-stream/extract.js:207:28)
    at oncontinue (/home/julian/repos/pelias/whosonfirst/node_modules/tar-stream/extract.js:64:10)
    at ondrain (/home/julian/repos/pelias/whosonfirst/node_modules/tar-stream/extract.js:84:5)
```

@trescube: any idea why this happens?

**Comment by orangejulius** [comment]
It looks like running individual downloads by editing the [list of bundles to download](https://github.com/pelias/whosonfirst/blob/master/download_data.js#L64-L75) helps as a workaround.

**Comment by easherma** [comment]
I ended up cloning from github.

**Comment by trescube** [comment]
Did cloning WOF obviate this issue?

**Comment by easherma** [comment]
@trescube cloning the WOF repo is more of an alternate way of downloading the data vs running this, so literally speaking this is still an issue with download_data.js

**Comment by orangejulius** [comment]
I'm also experiencing this. I don't remember which bundles it was, but even downloading one bundle at a time doesn't fix everything. It's true that downloading WOF via git is a workaround, but there's still an interesting bug in this script.

**Comment by easherma** [comment]
FYI tried this with ES 2.0 and the new production repo and got the same error

**Comment by gosom** [comment]
I am experiencing the same.
Can somebody write what is the workaround in detail?
