### ISSUE TITLE
Error installing and starting

### ISSUE THREAD

**Issue by easherma** [pelias/whosonfirst#120]
```
 pelias-whosonfirst@ start /data/pelias-2/whosonfirst
> node import.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/pelias-2/whosonfirst/node_modules/pelias-config/node_modules/mergeable/lib/Mergeable.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! pelias-whosonfirst@ start: `node import.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pelias-whosonfirst@ start script 'node import.js'.
npm ERR! This is most likely a problem with the pelias-whosonfirst package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node import.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pelias-whosonfirst
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pelias-whosonfirst
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/pelias-2/whosonfirst/npm-debug.log
```

**Comment by orangejulius** [comment]
This looks like another issue related to out of date dependencies, which NPM unfortunately allows to happen easily. `rm -rf node_modules && npm i` is the most reliable way to fix it that I know of :/
