### ISSUE TITLE
Problem downloading data with 2.9 ? (works in 2.8)

### ISSUE THREAD

**Issue by rjpereira** [pelias/whosonfirst#200]
When running npm run download --admin-only I get error below, when it is ok in 2.8. Any idea why ?

+ npm run download --admin-only

> pelias-whosonfirst@0.0.0-semantic-release download /root/whosonfirst
> node download_data.js

fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/mnt/data/whosonfirst/meta/whosonfirst_bundle_index.txt'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.statSync (/root/whosonfirst/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.<anonymous> (/root/whosonfirst/src/bundleList.js:22:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

On an unrelated note, and possibly not the right forum (is there any mailing list or community to ask questions rather then raising issues?), is it normal that after download admin data and loading data on another "package" I receive plenty of errors such as the ones below. The loaded data seems to be fine but wanting to check if there is something to correct. Thanks.

2017-02-19T21:24:01.405Z - info: [admin-lookup:worker] Done loading dependency
2017-02-19T21:24:01.405Z - info: [admin-lookup:worker] dependency finished loading 38 features in 0.288 secs
2017-02-19T21:24:01.448Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'dependency' } 'Worker dependency just told me it loaded!'
2017-02-19T21:24:01.664Z - error: [wof-pip-service:loadJSON] exception occured parsing /mnt/data/whosonfirst//data/110/850/0085/1108500085.geojson: Error: ENOENT: no such file or directory, open '/mnt/data/whosonfirst//data/110/850/0085/1108500085.geojson'
2017-02-19T21:24:01.669Z - error: [wof-pip-service:loadJSON] exception occured parsing /mnt/data/whosonfirst//data/110/875/6865/1108756865.geojson: Error: ENOENT: no such file or directory, open '/mnt/data/whosonfirst//data/110/875/6865/1108756865.geojson'
2017-02-19T21:24:01.669Z - error: [wof-pip-service:loadJSON] exception occured parsing /mnt/data/whosonfirst//data/110/875/6867/1108756867.geojson: Error: ENOENT: no such file or directory, open '/mnt/data/whosonfirst//data/110/875/6867/1108756867.geojson'
20

**Comment by orangejulius** [comment]
Hey @rjpereira,
Thanks for reporting this. I think we fixed the issue you're seeing in https://github.com/pelias/whosonfirst/pull/199, which we forgot to put into a release. 2.9.1 which was just made should fix your problem. Let us know!
