### ISSUE TITLE
"importPlace" must be a string

### ISSUE THREAD

**Issue by missinglink** [pelias/whosonfirst#260]
I assumed `importPlace` could be an integer or a string but this turns out not to be true.

Could we possibly relax this requirement, I can imagine other developers expecting they can define integers as the native number type in their `pelias.json`?

```bash
    docker: Error: "importPlace" must be a string
    docker: at Object.generate (/home/pelias/repos/whosonfirst/node_modules/pelias-config/index.js:29:13)
    docker: at Object.<anonymous> (/home/pelias/repos/whosonfirst/utils/download_data.js:1:105)
    docker: at Module._compile (module.js:409:26)
    docker: at Object.Module._extensions..js (module.js:416:10)
    docker: at Module.load (module.js:343:32)
    docker: at Function.Module._load (module.js:300:12)
    docker: at Function.Module.runMain (module.js:441:10)
    docker: at startup (node.js:139:18)
    docker: at node.js:968:3
```

```javascript
        "imports": {
          "whosonfirst": {
            "datapath": "/home/pelias/data/whosonfirst",
            "importVenues": false,
            "importPostalcodes": false,
            "importPlace": 101715829,
            "api_key": "mapzen-ry6wrsG"
          }
        }
```

**Comment by orangejulius** [comment]
+1 from me. I did this too and mentioned it in the initial review. Not sure if Joi supports it but it would be very nice if we could figure something out.

**Comment by dianashk** [comment]
We can definitely make it more flexible. Thanks for creating the issue to track the change.
