### ISSUE TITLE
Failed to get meta data

### ISSUE THREAD

**Issue by tonyk345** [pelias/whosonfirst#305]
OS: Mac 10.12.6
Docker: 17.09

When using the whosonfirst docker image to run "npm run download" the entire USA I get the error "failed to get meta data" If I use a more granular location like city or state, the download completes without issue.

Here is my pelias config for whosonfirst:
`"whosonfirst": {
      "datapath": "/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true,
      "importPlace": "85633793",
      "api_key": "*******"
    },`

Here is the error log:
```info: [download_data_filtered] Finished generating metafile for county
info: [download_data_filtered] previous meta file found /data/whosonfirst/meta/wof-localadmin-latest.csv
error: [download_data_filtered] 504
error: [download_data_filtered] [generateMetafiles] Error: failed to get place info
info: [download_data_filtered] Finished generating metafile for localadmin failed to get meta data for localadmin
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (failed to get meta data for localadmin)
    at DestroyableTransform.emit (events.js:144:17)
    at DestroyableTransform.onerror (/code/pelias/whosonfirst/node_modules/stream-array/node_modules/readable-stream/lib/_stream_readable.js:563:52)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at onwriteError (/code/pelias/whosonfirst/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:427:12)
    at onwrite (/code/pelias/whosonfirst/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:448:11)
    at WritableState.onwrite (/code/pelias/whosonfirst/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/code/pelias/whosonfirst/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:3)
    at TransformState.afterTransform (/code/pelias/whosonfirst/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /code/pelias/whosonfirst/node_modules/pelias-parallel-stream/index.js:20:16```

**Comment by orangejulius** [comment]
Hey @tonyk345,
Thanks for writing in. We've seen this too and would like to fix it, but realistically even if we fixed it, the download might take too long to be worthwhile. It's a lot of extra work for both the downloader and the Who's on First API server to filter data within an entire country.

My recommendation for a workaround would be to remove the `importPlace` property from your config to download the whole world's WOF data. It will use pre-packaged bundles which are a lot quicker and easier to download. I think a large percentage of WOF data is for the US, so you wouldn't get too much extra data.

If that extra data is really a deal breaker, it wouldn't be too hard to set up the importer itself to do the filtering (it's already reading through all the records anyway). In fact, that's probably how we'd end up implementing country downloads if we wanted to make it work seamlessly. If you do want to dive into the code to work on that filtering we'd be glad to help you craft a pull request that we would happily merge. Let us know :)
