### ISSUE TITLE
npm run download throws an error about a "handshake failure"

### ISSUE THREAD

**Issue by sftsang** [pelias/whosonfirst#378]
Looks like this:

https://github.com/pelias/whosonfirst/blob/master/utils/download_data_filtered/getPlaceInfo.js

references this URL:

https://whosonfirst-api.mapzen.com

which doesn't seem to work anymore and is causing this error:

```
> pelias-whosonfirst@0.0.0-semantic-release download /home/ubuntu/pelias/whosonfirst
> node ./utils/download_data.js "--admin-only"

2018-08-07T21:30:09.534Z - info: [download_data_filtered] Getting parent ids
2018-08-07T21:30:09.586Z - error: [download_data_filtered] { Error: write EPROTO 139649456498496:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
after parents failed to get place info undefined
2018-08-07T21:30:09.589Z - error: [download_data_filtered] "failed to get place info"
```

Is there an alternative place to get access to the API so that we can get the data that we  are looking for? Are we supposed to get the data in another way now?

Thanks.

**Comment by orangejulius** [comment]
Hey @sftsang,
This code is no longer used, since the Mapzen API stopped working after Mapzen shut down in January. Are you using the latest code? It should be able to download the WOF data through other means.

To keep things more clear, I've opened https://github.com/pelias/whosonfirst/pull/379 to remove this code so it can't cause any more confusion.
